### ISSUE TITLE
[polaris.shopify.com] Props table feedback

### ISSUE THREAD

**Issue by vicvans20** [Shopify/polaris-react-archive#7017] opened 2022-08-25 01:03 UTC
Props section is missing some props especifications like:
* breadcrumbs
* title
* subtitle
* titleMetadata
* pagination

I know the source code got examples of them, but having all the props for quick reference would be useful.

**Comment by chloerice** [comment] 2022-08-25 14:37
Hey @vicvans20 👋🏽 Thanks for raising this! There's a fix in progress in #6757. Gonna close this as it's a duplicate of #6779.

**Closed as completed by chloerice** 2022-08-25 14:37 UTC
