### ISSUE TITLE
[polaris.shopify.com] Feedback - Missing props overview

### ISSUE THREAD

**Issue by schonert** [Shopify/polaris-react-archive#6377] opened 2022-06-24 04:34 UTC
Hey - great brushup! Neat and easy to find components without having to know their context.

One thing that is missing is the props overview with the option to play around with values. Was a great way to explore components and do a quick MVP of what you're trying to achieve.

**Comment by alex-page** [comment] 2022-06-24 05:08
Hey @schonert closing this as it's a duplicate of https://github.com/Shopify/polaris/issues/6371

**Closed as completed by alex-page** 2022-06-24 05:08 UTC
