### ISSUE TITLE
[polaris.shopify.com] Modal props table feedback — unclear how to create tertiary action

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/polaris-react-archive#6777] opened 2022-07-27 13:21 UTC
It would be nice to include how to create a tertiary action.
Tried fullWidth plain button but it doesn't seem to work

**Comment by martenbjork** [comment] 2022-07-27 15:22
Hi! I agree, this is confusing. Adding to the backlog.

**Comment by chloerice** [comment] 2022-08-19 16:24
Hey @artyrcheek, the modal accepts two action props: `primaryAction` accepts an object of type [ComplexAction](https://github.com/Shopify/polaris/blob/112d144d2ed68e1937fc9d2f31f9643523ebd801/polaris-react/src/types.ts#L214) and `secondaryActions` accepts an array of objects of type [ComplexAction](https://github.com/Shopify/polaris/blob/112d144d2ed68e1937fc9d2f31f9643523ebd801/polaris-react/src/types.ts#L214). 

|`primaryAction`|`secondaryActions`|
|---|---|
|<img width="201" alt="Screen Shot 2022-08-19 at 12 32 00 PM" src="https://user-images.githubusercontent.com/18447883/185667783-4e9883ff-91de-4a07-b5b1-f591daf8ea0f.png">|<img width="200" alt="Screen shot of props list for secondary actions" src="https://user-images.githubusercontent.com/18447883/185667348-9d3d424b-ba44-470b-a12a-631f0a3d1f15.png">|

Closing as this is a duplicate of #6599 and is being worked on in #6757

**Closed as completed by chloerice** 2022-08-19 16:24 UTC
