### ISSUE TITLE
[polaris.shopify.com] Props table feedback - spell out the Prop types of component prop variables

### ISSUE THREAD

**Issue by zakwarsame** [Shopify/polaris-react-archive#6977] opened 2022-08-17 20:25 UTC
Example: I keep forgetting the `Spacing` [types of the `Stack` component](https://github.com/Shopify/polaris/blob/e5eb700321c7ddf4fd3bd8679dfcebbc1514e3d4/polaris-react/src/components/Stack/Stack.tsx#L9). Is there an easier way to find these on polaris.shopify.com or is checking the source code the only way currently?

<details>
  <summary> Same goes for Alignment, Distribution etc. </summary>

![Stack Props on polaris.shopify.com](https://screenshot.click/17-23-90967-27596.png)

</details>

**Comment by chloerice** [comment] 2022-08-18 15:36
Hey @zakwarsame 👋🏽 I'm sorry for the inconvenience as we transition from the old site to the new site. We are working on improving the props table, you can follow along in https://github.com/Shopify/polaris/pull/6757.

Closing as this is a duplicate of https://github.com/Shopify/polaris/issues/6599

**Closed as completed by chloerice** 2022-08-18 15:36 UTC
Labels: polaris.shopify.com
