### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/action-list)

### ISSUE THREAD

**Issue by kuipou** [Shopify/polaris-react-archive#6393] opened 2022-06-24 17:32 UTC
It would be easier if we didn't have toggle between preview and code

**Comment by alex-page** [comment] 2022-06-27 15:56
Thanks @kuipou. This is a duplicate of https://github.com/Shopify/polaris/issues/6397

**Closed as completed by alex-page** 2022-06-27 15:56 UTC

**Comment by alex-page** [comment] 2022-06-27 15:59
Moving this feedback to https://github.com/Shopify/polaris/issues/6381. Sorry!
