### ISSUE TITLE
Tabs taking keypress focus

### ISSUE THREAD

**Issue by alexdover** [Shopify/polaris-react-archive#74] opened 2017-05-31 09:09 UTC
# Issue summary

I'm using the tabs component to render a settings page which has multiple forms. The documentation is a little light on how to code up the panel contents, but I have used onSelect to toggle between the forms I have.

What I have now found and can't seem to stop is that every time I press a key in the forms, the tabs grab the focus.

I am new to React so apologies if I am missing something obvious!

## Expected behavior

When completing a form on the page the tabs do not take the focus.

## Actual behavior

Typing into a field on the same page as a tab sees tab take the focus

## Specifications

- Polaris version: 1.0.2
- React version: 15.5.4
- Browser: Chrome
- Device: Macbook Pro
- Operating System: MacOs Sierra

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment] 2017-05-31 18:23
Thanks for the issue, @alexdover, confirmed that this is indeed happening. I'll have a fix up in the next version, which I am hoping to release on Friday. Will close this issue once it's addressed.

**Comment by alexdover** [comment] 2017-06-01 07:45
OK, thanks - at least it wasn't just a newbie issue!

**Comment by lemonmade** [comment] 2017-06-19 17:48
Should be fixed by v1.1.0

**Closed as completed by lemonmade** 2017-06-19 17:48 UTC

**Comment by alexdover** [comment] 2017-06-19 20:15
Great, thanks!

**Comment by cbodtorf** [comment] 2017-06-20 16:54
I just upgraded to polaris v1.1.1

Still having this issue.

**Comment by lemonmade** [comment] 2017-06-21 18:04
@cbodtorf can you provide some markup that exhibits this issue? I am unable to reproduce.
