### ISSUE TITLE
Card section without border

### ISSUE THREAD

**Issue by issamwahbi** [Shopify/polaris-react-archive#4661] opened 2021-11-17 13:33 UTC
## Issue summary

When using a Card Section inside a Stack to have 2 sections in one row. The border of the Card section are not displayed any more

## Expected behavior

The borders must be displayed 

## Actual behavior

the borders are note displayed

## Steps to reproduce the problem

        <Page>
          <Layout>
            <Layout.Section >
                <Card subdued={true} sectioned={true}>
                    <Stack distribution="fillEvenly">
                        <Stack.Item>
                            <Card.Section>
                                <p>Section 1</p>
                            </Card.Section>
                        </Stack.Item>
                        <Stack.Item>
                            <Card.Section>
                                <p>Section 2</p>
                            </Card.Section>
                        </Stack.Item>
                    </Stack>
                </Card>
            </Layout.Section>
          </Layout>
        </Page>
## Reduced test case

The best way to get your bug fixed is to provide a reduced test case. This [CodeSandbox template](https://codesandbox.io/s/q82mlq0m26) is a great starting point.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: latest
- Browser: Chrome
- Device: PC
- Operating System: Windows

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

**Comment by dleroux** [comment] 2021-12-07 16:11
👋 Hi @issamwahbi, Thanks for reporting this, but the issue is with the current mark-up. A <Card.Section> is meant to be a direct child of Card, and they are stacked as rows, not columns. What you probably want is something like this:
```
<Card subdued={true} sectioned>
        <Stack distribution="fillEvenly">
          <div style={{borderRight: '1px solid var(--p-border)'}}>
            <p>Section 1</p>
          </div>
          <p>Section 2</p>
        </Stack>
      </Card>
```

I'll close this issue, but feel free to reopen if that's not the case.

**Closed as completed by dleroux** 2021-12-07 16:11 UTC
Labels: Bug
