### ISSUE TITLE
<EmbeddedApp> forceRedirect option is not redirecting

### ISSUE THREAD

**Issue by jimmyn** [Shopify/polaris-react-archive#45] opened 2017-05-04 13:32 UTC
## Expected behavior

 `EmbeddedApp` component with `forceRedirect: true` should redirect the app to the relative admin path when not rendered in an iframe

## Actual behavior
I've inspected the code and it seems that it only sends the message but never actually redirects.
https://github.com/Shopify/polaris/blob/master/src/embedded/easdk/EASDK.ts#L58

I initialize the component like this 

```
<EmbeddedApp
   shopOrigin={shopOrigin}
   apiKey={apiKey}
   forceRedirect>
   {children}
</EmbeddedApp>
```

**Comment by lemonmade** [comment] 2017-05-04 14:05
Thanks for the issue, @jimmyn. This is a duplicate of https://github.com/Shopify/polaris/issues/28 I think. We have a fix almost ready to go, will be part of the next release.

**Closed as completed by lemonmade** 2017-05-04 14:05 UTC
