### ISSUE TITLE
[polaris.shopify.com] General Feedback

### ISSUE THREAD

**Issue by realpratiknikam** [Shopify/polaris-react-archive#6374] opened 2022-06-24 01:03 UTC
New webpage looks clean but here are my concerns:

1. Couldn't find props which are crucial to configure every component.
2. Code window stays as is even when you switch to different component. Should fallback to preview.
3. Categorization for components was really helpful.
4. All content under "Best Practices" feels monogamous. Some kind of sections or easy way of differentiation would help.
5. Preview/code switchers are very small so have to be very specific with mousepad when selecting.

Here are my favorites:

1. Search interface is great!
2. Dark mode!
3. Related components section is helpful!

**Comment by alex-page** [comment] 2022-06-24 05:09
Thanks @pratiknikam. 1 is a duplicate of this issue https://github.com/Shopify/polaris/issues/6371. I'll leave this open as there is other useful feedback. Cheers.

**Comment by martenbjork** [comment] 2022-06-24 08:09
Thanks for this detailed feedback! I captured a few more issues based on this. 🙂

**Closed as completed** 2023-06-20 03:32 UTC
Labels: polaris.shopify.com, no-issue-activity
