### ISSUE TITLE
Color Picker example broken, throwing JS errors

### ISSUE THREAD

**Issue by chrispappas** [Shopify/polaris-react-archive#24] opened 2017-04-24 16:46 UTC
# Issue summary

The color picker example is broken. The page loads but on interaction with the components, JS errors occur and the component does not work.

https://polaris.shopify.com/components/forms/color-picker#navigation 

## Expected behavior

The color picker component should allow you to alter the options for color hue and transparency

## Actual behavior

The color does not change in the picker and in the JS console, the following error occurs.

<details>
ColorPicker.tsx:106 Uncaught TypeError: (0 , o.onChange) is not a function
    at t.value (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:232008)
    at t.value (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:87981)
    at t.value (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:87466)
    at Object.r (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:44298)
    at a (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:40418)
    at Object.s [as executeDispatchesInOrder] (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:40633)
    at d (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:22704)
    at m (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:22830)
    at Array.forEach (native)
    at r (https://polaris.shopify.com/assets/demo-552e714115176d1f07c8.js:1:69554)
</details>

## Steps to Reproduce the Problem

1. Visit the Color picker example page
2. Click on any of the elements (square gradient, vertical color bar, vertical transparency bar)
3. No visible UI changes
4. Errors are shown in the developer tools console

## Specifications

- Polaris version: N/A
- React version: N/A
- Browser: Chrome 57
- Device: Macbook Pro
- Operating System: OSX 10.12.3

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by chrispappas** [comment] 2017-04-24 17:46
The same error occurs in Chrome 58 and in Firefox 52.0.2 and 53.0, all on OSX 10.12.3

**Comment by chrispappas** [comment] 2017-04-24 17:49
Realizing this may be intentional, as many of your examples do not have an onChange event set. Adding a noop or some other feedback to show that the color has been selected, and displaying the color value format (hex? hsl? rgba?) would be very helpful.

**Comment by lemonmade** [comment] 2017-04-24 20:46
Hey @chrispappas, thanks for the issue. We are definitely aware of the errors/ weirdness that is caused by not having some form of change handler for many of our components. We are working through some ideas of how to solve this and should have something up in the near future. I'll keep this issue updated as we work through the underlying problem.

**Comment by lemonmade** [comment] 2017-05-11 13:14
Fixed in the live version of the style guide.

**Closed as completed by lemonmade** 2017-05-11 13:14 UTC
