### ISSUE TITLE
[polaris.shopify.com] Feedback (on page /components/tabs)

### ISSUE THREAD

**Issue by Abhinav-42** [Shopify/polaris-react-archive#6400] opened 2022-06-25 18:30 UTC
Nice work on the dark mode and all. Please put some focus on functionality as well. Where can I find the properties to pass to the Tab component? In fact, I am not able to find the properties for any components at all and it was there in the earlier version. Perhaps instead of making everything look cool, put some focus on how helpful the content is for the developers.

**Comment by chloerice** [comment] 2022-06-26 00:40
Hey @Abhinav-42 👋🏽 We appreciate you taking the time to share your feedback. I'm closing this issue as it's a duplicate of https://github.com/Shopify/polaris/issues/6371.

The new site will continue to be iterated on, this is on our radar so stay tuned! In the meantime, you can still use the props table and explorer on the [legacy site](https://legacy.polaris.shopify.com).

**Closed as completed by chloerice** 2022-06-26 00:40 UTC
