### ISSUE TITLE
 Issue with my own settings breadcrumb opening Shopifys settings page

### ISSUE THREAD

**Issue by cargix1** [Shopify/polaris-react-archive#116] opened 2017-07-02 22:17 UTC
# Issue summary

When clicking my Settings or Orders breadcrumb links i'm automatically getting redirected to Shopifys settings and orders pages. 

<img width="1280" alt="screen shot 2017-07-02 at 23 08 01" src="https://user-images.githubusercontent.com/9730290/27773892-57945950-5f7c-11e7-8500-92d9b4cdef49.png">

## Expected behavior

I'd expect that when I have the url set to `/orders` or `/settings` within my breadcrumb that it would redirect the user to my apps Settings and Orders pages and not Shopifys. 

## Actual behavior

At the moment when I click Settings i'm redirected to Shopify's settings page and when I click Orders i'm redirected to Shopify's orders page.  

## Steps to Reproduce the Problem

  1. Create a page using the following breadcrumb setup

```
<Page title="Design"
            breadcrumbs={[{content: 'Settings', url: '/settings' }]}
            primaryAction={{content: 'Save'}}>
     <p>Hello World!</p>
</Page>
```

  2. Create a route within React that also points to /settings. 

  4. Click the Settings link within the breadcrumb. 

  5. You should now be redirected to Shopify's settings page, not the apps settings page like i'd expect. 

I've noticed a bunch of comments in two other closed issues #97 and #78, but nothing I do seems to help. 

## Specifications

- Polaris version: 1.1.1
- React version: 15.4.2
- Browser: Chrome
- Device: Macbook Pro
- Operating System: Sierra

**NOTE:** This repo is only used for reporting issues and new feature requests. We are not accepting pull requests at this point in time.

**Comment by lemonmade** [comment] 2017-07-04 17:27
Thanks for the issue, @cargix1. Do you know if this behaviour is different when using the EASDK directly? We will take a look at this, but I think a workaround in the interim is to pass the full URL (including your app's domain name), which should correctly take them to your app's page (and only refresh the iframe, not the entire page).

**Comment by EvilLooney** [comment] 2017-07-11 21:36
@lemonmade Would it be possible to add `onAction` properties to the breadcrumbs? That way, the app would not need to reload and I could just render my new component.

**Comment by cargix1** [comment] 2017-07-12 11:38
Hey @lemonmade sorry for the delay. 

Using the apps full url doesn't appear to work i'm afraid. Instead we get the EASDK loading bar appear at the top of the page. It shows real slow signs of progress, after some time the blue bar fills the entire page, but ultimately nothing happens. The user is left in the same spot. 

I had my url set like this: `breadcrumbs={[{content: 'Dashboard', url: 'https://app.storepickup.dev/'}]}`. Which should have redirected the user back to our Dashboard.

**Comment by cargix1** [comment] 2017-07-18 15:54
Hey @lemonmade, did you have any further updates on this one? We're really close to launching :)

**Comment by lemonmade** [comment] 2017-07-19 00:13
Hey, sorry for the delay. Were there any errors in the console when this happened? Can you show the markup you are getting for the breadcrumb link that you are clicking on (it will be in the admin frame, instead of in your app, but I am curious what ends up coming to). Also, can you check what `window.location.hostname` is in your app? This is what is used to determine if the `url` that is provided is part of your application (and, therefore, should change the location on the `iframe`).

**Comment by cargix1** [comment] 2017-07-19 07:16
No problem @lemonmade! 

Here's my javascript code:

<img width="640" alt="screen shot 2017-07-19 at 08 09 50" src="https://user-images.githubusercontent.com/9730290/28354935-b7c3b58e-6c59-11e7-9b96-7eb036c3f3cb.png">

And this is the html is generates:

<img width="1060" alt="screen shot 2017-07-19 at 08 07 50" src="https://user-images.githubusercontent.com/9730290/28354948-c8c1d33e-6c59-11e7-8041-b508d54b6a48.png">

This is what's showing in my console before the click:

<img width="1505" alt="screen shot 2017-07-19 at 08 12 10" src="https://user-images.githubusercontent.com/9730290/28354993-1031cb7a-6c5a-11e7-88a1-29cc94c64a48.png">

And this is what shows in my console once i've clicked the Dashboard breadcrumb:

<img width="1503" alt="screen shot 2017-07-19 at 08 13 14" src="https://user-images.githubusercontent.com/9730290/28355020-2eb98916-6c5a-11e7-8165-4654f5f88c5f.png">

If I `console.log(window.location.hostname)` within my code it's showing as `app.storepickup.dev`.

If I type `window.location.hostname` directly in the console I get `shopifyextras.myshopify.com`.

Anything else you need just let me know :)

**Comment by cargix1** [comment] 2017-07-19 15:20
@lemonmade just given it a go. I tried just `app.storepickup.dev` as shown below:

<img width="704" alt="screen shot 2017-07-19 at 16 14 01" src="https://user-images.githubusercontent.com/9730290/28374663-5d27a3ee-6c9d-11e7-98ef-0c4a8c668da4.png">

Nothing shows in the console other then the Select warning. You'll notice that the loading bar appears at the top of the screen though. But nothing else happens. 

<img width="1467" alt="screen shot 2017-07-19 at 16 13 22" src="https://user-images.githubusercontent.com/9730290/28374820-c56a5a3c-6c9d-11e7-843f-62d5c177dce1.png">

Here's the HTML generated: 

<img width="1031" alt="screen shot 2017-07-19 at 16 19 34" src="https://user-images.githubusercontent.com/9730290/28374926-12e2996e-6c9e-11e7-9c84-65e698ef8e03.png">

I also tried `https://app.storepickup.dev`and I get the exact same thing, heres the HTML generated:

<img width="944" alt="screen shot 2017-07-19 at 16 18 53" src="https://user-images.githubusercontent.com/9730290/28374899-047f8102-6c9e-11e7-944c-965ce9cb7ffc.png">

**Comment by cargix1** [comment] 2017-08-16 23:52
Hey @lemonmade,

Hope you're well. I'm now trying to link orders from my apps Dashboard to the edit order page of Shopify (https://shopifyextras.myshopify.com/admin/orders/5664679047). When clicking the link I get the reverse of the above and i'm kept within my own app. 

Here's an example of the outputted HTML. 

<img width="683" alt="screen shot 2017-08-17 at 00 47 00" src="https://user-images.githubusercontent.com/9730290/29390065-e9bd9dfa-82e5-11e7-89bd-36f579a89ba5.png">

I've tried using both the following without success:

```
<Link url={`/orders/5664679047`}>{details.external_name}</Link>
```

```
<Link url={`/orders/5664679047`}>{details.external_name}</Link>
```

Both will display a 404 within my own app rather then automatically redirecting to https://shopifyextras.myshopify.com/admin/orders/5664679047 like I expected.

Any updates on this would be great as we're hoping to go live before the end of the month.

Thanks,

Andy

**Comment by cargix1** [comment] 2017-08-16 23:52
Doh! Sorry closed by accident, re-opened.

**Comment by lemonmade** [comment] 2017-08-17 14:44
@cargix1 the issue of opening an admin page from your app can be solved by cancelling the default behaviour of the link, and instead using `this.context.easdk.redirect()`: https://github.com/Shopify/polaris/blob/master/documentation/Embedded%20apps.md#easdkredirect

**Comment by cargix1** [comment] 2017-08-17 18:38
@lemonmade works perfect for the admin page links thanks! 

Just the original issue still to resolve :)

**Comment by rkbhochalya** [comment] 2017-08-18 03:08
@cargix1 the issue is still closed ;) @lemonmade I'm having the exact same issue. App links in breadcrumb and page actions simply don't work. Please check screenshots and information provided by @cargix1 above.

**Comment by cargix1** [comment] 2017-09-18 09:38
Hey @lemonmade,

Any update on this one? It's the only thing stopping us from launching now :) 

Thanks,

Andy

**Comment by rkbhochalya** [comment] 2017-09-18 10:05
@lemonmade same for us :) we really need this fixed soon.

**Comment by cargix1** [comment] 2017-09-21 09:07
Hey @rkbhochalya,

I think i've found a work around for now. I created the following helper function:

```
export function generateAdminUrl(path) {
  return '/admin/apps/YOUR_APP_ID_HERE/' + path;
}
```
And then call it like this:

```
breadcrumbs={[{ content: 'Outlets', url: generateAdminUrl('/outlets') }]}
```

Just replace the YOUR_APP_ID_HERE string with your own.

<img width="775" alt="screen shot 2017-09-21 at 10 05 40" src="https://user-images.githubusercontent.com/9730290/30687885-7d6c990e-9eb4-11e7-946b-b183aaab44ba.png">

Not ideal, but it works, so we can #ship!

**Comment by tmlayton** [comment] 2017-10-04 17:26
Hi @cargix1 and @rkbhochalya, this will be fixed as of 1.7.0. 

- A `url` beginning with `/` (e.g. `/orders`) will open in Shopify
- a relative `url` without a leading `/` (e.g. `orders`) will open within the app (the redirection has been fixed)
- an absolute `url` will open within the app if the host matches the app host and a protocol is present (e.g. `https://yourapp.com/orders`)
- and an absolute `url` with a different host will open in a new window (e.g. `https://otherapp.com/orders`).

If the `target` based on the `url` is not what you want, as of 1.7.0 you will be able to define your own `target`. Supported values are [`app`, `new`, `parent`, and `shopify`](https://help.shopify.com/api/sdks/shopify-apps/embedded-app-sdk/methods#button-objects).

And @EvilLooney, `onAction` will be supported on breadcrumbs too as of 1.7.0

**Comment by cargix1** [comment] 2017-10-04 17:32
Wahoooooo! Thanks so much @tmlayton very good news :)

**Comment by tmlayton** [comment] 2017-10-06 20:08
v1.7.0 has been released!

**Closed as completed by tmlayton** 2017-10-06 20:08 UTC
