### ISSUE TITLE
Props table still missing for some components

### ISSUE THREAD

**Issue by jbalsas** [Shopify/polaris-react-archive#6987] opened 2022-08-18 21:45 UTC
## Issue summary

Some components are still missing their props tables. Here's a potential list of affected components:
- [Badge](https://polaris.shopify.com/components/badge)
- KeypressListener (not currently listed)
- [Tag](https://polaris.shopify.com/components/tag)
- [Textfield](https://polaris.shopify.com/components/text-field)

My best guess (without looking too deep into it) is that these components are exporting a `NonMutuallyExclusiveProps` that somehow we fail to match back to the component 🤷 

## Expected behavior
These components should have their props listed just as the rest of components

## Actual behavior
Prop tables for these are just missing 😢 

## Steps to reproduce the problem
1. Navigate to any of the aforementioned urls and verify that the props table is missing even though the components have props

| Badge | Tag | Text field |
| --- | --- | --- |
| [![badge](https://user-images.githubusercontent.com/905006/185501315-9adc55e1-2a82-41d4-adf9-98c64ecfbbff.png)](https://polaris.shopify.com/components/badge) | [![tag](https://user-images.githubusercontent.com/905006/185501324-a5c1f4fb-8f8f-4349-bd35-a376002c7c8b.png)](https://polaris.shopify.com/components/tag) | [![textfield](https://user-images.githubusercontent.com/905006/185501327-6eb658fd-aae6-4d1b-94ee-3d992db63d60.png)](https://polaris.shopify.com/components/text-field) |

PS: There seem to be related open issues at the moment (https://github.com/Shopify/polaris/issues/6371, https://github.com/Shopify/polaris/issues/6601, https://github.com/Shopify/polaris/issues/6779) but I think this one is different in nature to those other ones.

**Comment by alex-page** [comment] 2022-08-22 14:29
Duplicate of https://github.com/Shopify/polaris/issues/6779. Feel free to add context there.

**Closed as completed by alex-page** 2022-08-22 14:29 UTC
Labels: polaris.shopify.com
